[package]
name = "typhoon-stdlib"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"
description = "Typhoon lang standard library"

[build-dependencies]
# Reference the 'tyc' binary from typhoon-cli
typhoon-cli = { workspace = true, artifact = "bin", bin = "tyc", lib = false }
